project:
  type: website
  render:
    - index.qmd
    - Par_villes/Saint_Girons.qmd
    - Par_villes/Rodez.qmd
    - Par_villes/Nimes.qmd
    - Par_villes/Toulouse.qmd
    - Par_villes/Auch.qmd
    - Par_villes/Montpellier.qmd
    - Par_villes/Tarbes.qmd
    - Par_villes/Perpignan.qmd
    - Par_villes/Albi.qmd
    - Par_villes/Montauban.qmd
    - Geographique.qmd
website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Pollution en Occitanie"
  # site-url: 
  repo-url: https://github.com/cmottier/PROJET-Pollution_en_Occitanie

  navbar:
    title: "Pollution en Occitanie"
    background: primary
    # search: true
    # tools:
    #   - icon: bicycle
    #     href: https://moodle.umontpellier.fr/course/view.php?id=22454
    #     text: Moodle
    #   - icon: github
    #     href: https://github.com/josephsalmon/HAX712X
    #     text: GitHub
    left:
      - text: Comparaison géographique
        menu: 
          - Geographique.qmd
      - text: Graphiques par villes
        menu: 
          - Par_villes/Saint_Girons.qmd
          - Par_villes/Rodez.qmd
          - Par_villes/Nimes.qmd
          - Par_villes/Toulouse.qmd
          - Par_villes/Auch.qmd
          - Par_villes/Montpellier.qmd
          - Par_villes/Tarbes.qmd
          - Par_villes/Perpignan.qmd
          - Par_villes/Albi.qmd
          - Par_villes/Montauban.qmd
      # - sidebar:Villes
  # sidebar:
  #   - id: Villes
  #     title: "Graphiques par villes"
  #     collapse-level: 2
  #     contents:
  #       - Par_villes/Saint_Girons.qmd
  #       - Par_villes/Rodez.qmd
  #       - Par_villes/Nimes.qmd
  #       - Par_villes/Toulouse.qmd
  #       - Par_villes/Auch.qmd
  #       - Par_villes/Montpellier.qmd
  #       - Par_villes/Tarbes.qmd
  #       - Par_villes/Perpignan.qmd
  #       - Par_villes/Albi.qmd
  #       - Par_villes/Montauban.qmd


format:
  html:
    toc: true
    theme:
      spacelab
      # light: spacelab
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    number-sections: false
    toc-depth: 3
    code-fold: true
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    grid: 
      body-width: 1800px
    # self-contained: true
    # fig-format: svg
    # css: custom.scss