project:
  type: website
  render:
    - index.qmd
    - PollutionEnOccitanie/Par_villes/Saint_Girons.qmd
    - PollutionEnOccitanie/Par_villes/Rodez.qmd
    - PollutionEnOccitanie/Par_villes/Nimes.qmd
    - PollutionEnOccitanie/Par_villes/Toulouse.qmd
    - PollutionEnOccitanie/Par_villes/Auch.qmd
    - PollutionEnOccitanie/Par_villes/Montpellier.qmd
    - PollutionEnOccitanie/Par_villes/Tarbes.qmd
    - PollutionEnOccitanie/Par_villes/Perpignan.qmd
    - PollutionEnOccitanie/Par_villes/Albi.qmd
    - PollutionEnOccitanie/Par_villes/Montauban.qmd
    - PollutionEnOccitanie/Comparaison_geo/Geographique.qmd
website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Pollution en Occitanie"
  # site-url: 
  repo-url: https://github.com/cmottier/PROJET-Pollution_en_Occitanie

  navbar:
    title: "Pollution en Occitanie"
    background: primary
    left:
      - text: Comparaison géographique
        menu: 
          - PollutionEnOccitanie/Comparaison_geo/Geographique.qmd
      - text: Graphiques par villes
        menu: 
          - PollutionEnOccitanie/Par_villes/Saint_Girons.qmd
          - PollutionEnOccitanie/Par_villes/Rodez.qmd
          - PollutionEnOccitanie/Par_villes/Nimes.qmd
          - PollutionEnOccitanie/Par_villes/Toulouse.qmd
          - PollutionEnOccitanie/Par_villes/Auch.qmd
          - PollutionEnOccitanie/Par_villes/Montpellier.qmd
          - PollutionEnOccitanie/Par_villes/Tarbes.qmd
          - PollutionEnOccitanie/Par_villes/Perpignan.qmd
          - PollutionEnOccitanie/Par_villes/Albi.qmd
          - PollutionEnOccitanie/Par_villes/Montauban.qmd


format:
  html:
    toc: true
    theme:
      spacelab
    html-math-method: katex
    number-sections: false
    toc-depth: 3
    code-fold: true
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    grid: 
      body-width: 1500px
